function [fitresult, gof] = createFit(logXN, logYL, logC)
%CREATEFIT(LOGXN,LOGYL,LOGC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : logXN
%      Y Input : logYL
%      Z Output: logC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jan-2018 10:18:20


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( logXN, logYL, logC );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
leg1=legend( h, 'Plane fitting the data', '$\log_{10}C$ vs. $\log_{10}N$, $\log_{10}(\hat{\lambda}_s / \lambda_f)$', 'Location', 'NorthEast' );
set(leg1,'Interpreter','latex');
% Label axes
xlabel('$\log_{10}N$','Interpreter','latex')
ylabel('$\log_{10}(\hat{\lambda}_s / \lambda_f)$','Interpreter','latex')
zlabel('$\log_{10}C$','Interpreter','latex')
grid on
view( 151.7, 23.6 );


