function [fitresult, gof] = createFit(logXN, logYL, logC)
%CREATEFIT(LOGXN,LOGYL,LOGC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : logXN
%      Y Input : logYL
%      Z Output: logC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jan-2018 10:18:20


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( logXN, logYL, logC );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'logC vs. logXN, logYL', 'Location', 'NorthEast' );
% Label axes
xlabel logXN
ylabel logYL
zlabel logC
grid on
view( 151.7, 23.6 );


